spring:
  application:
    name: hmily-demo-bank1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank1?characterEncoding=utf-8
    username: root
    password: Anbang713
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  servlet:
    context-path: /bank1
  port: 9011
eureka:
  client:
    service-url:
      defaultZone: http://Anbang713:pwd713@localhost:9010/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 30 # 10秒不发送就过期
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 30
      retryMax: 30
      scheduledDelay: 30
      scheduledThreadMax: 10
      repositorySupport: db
      started: true
      hmilyDbConfig:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hmily?useUnicode=true
        username: root
        password: Anbang713